// Copyright 2021 Prescryptive Health, Inc.

export enum SecurePinStateActionKeys {
  NAVIGATE_TO_VERIFY_PIN = 'NAVIGATE_TO_VERIFY_PIN',
  SET_HAS_PIN_MISMATCHED = 'SET_HAS_PIN_MISMATCHED',
  SET_CREATED_PIN_TO_STATE = 'SET_CREATED_PIN_TO_STATE',
  SET_PIN_TO_BE_VERIFIED = 'SET_PIN_TO_BE_VERIFIED',
  SET_PIN_STATE_DEFAULT = 'SET_PIN_STATE_DEFAULT',
  SET_NUMBER_OF_FAILED_ATTEMPTS_TO_VERIFY = 'SET_NUMBER_OF_FAILED_ATTEMPTS_TO_VERIFY',
  SET_ERROR_CODE = 'SET_ERROR_CODE',
  SET_AUTH_EXPERIENCE = 'SET_AUTH_EXPERIENCE',
  SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED',
}
