// Copyright 2021 Prescryptive Health, Inc.

import { Logger } from 'winston';
import { IConfiguration } from '../configuration';

export const configurationMock: IConfiguration = {
  auth0: {
    clientId: 'auth0-api-client-id',
    clientSecret: 'auth0-api-client-secret',
    tokenApi: 'auth0-token-api',
    audienceAccumulators: 'auth0-audience-accumulators',
    audienceClaims: 'auth0-audience-claims',
    audienceIdentity: 'auth0-audience-identity',
  },
  childMemberAgeLimit: 13,
  gearsApiSubscriptionKey: 'mock-key',
  redisAuthPass: 'redis-auth-pass',
  redisDeviceTokenKeyExpiryTime: 30,
  redisHostName: 'redis-host',
  redisPinKeyExpiryTime: 1200,
  redisPinVerificationKeyExpiryTime: 1800,
  redisIdentityVerificationKeyExpiryTime: 3600,
  redisPort: 9999,
  redisPinResetScanDeleteCount: '1000',
  redisPersonCreateKeyExpiryTime: 100,
  redisPhoneNumberRegistrationKeyExpiryTime: 100,
  redisNearbyPharmaciesKeyExpiryTime: 100,
  redisCMSContentKeyExpiryTime: 100,
  partnerJwksMap: new Map(),
  platformApiUrl: 'platform-url',
  platformGearsApiUrl: 'platform-gears-url',
  platformPrescriptionApiHeaderKey: 'platform-header-key',
  platformApiClientId: 'platform-client-id',
  platformApiClientSecret: 'platform-client-secret',
  platformApiResource: 'platform-resource',
  platformApiTenantId: 'platform-tenant-id',
  pharmacyPortalApiUrl: 'pharmacy-url',
  pharmacyPortalApiTenantId: 'pharmacy-portal-tenant-id',
  pharmacyPortalApiClientId: 'pharmacy-portal-client-id',
  pharmacyPortalApiClientSecret: 'pharmacy-portal-client-secret',
  pharmacyPortalApiScope: 'pharmacy-portal-scope',
  pricingApiHeaderKey: 'pricing-header-key',
  contentApiUrl: 'content-api-url',
  contentApiSmartPricePassword: 'user',
  contentApiSmartPriceUserName: 'pwd',
  supportEmail: 'test-email',
  serviceBusConnectionString: 'fake-connection-string',
  twilioMessagingFromPhoneNumber: 'twilio-messaging-from-phone-number',
  twilioVerificationServiceId: 'twilio-id',
  testPaymentsKeyPrivate: 'test mock private',
  testPaymentsKeyPublic: 'test mock public',
  topicNameHealthRecordEvent: 'fake-health-record-topic',
  topicNameAppointmentCancelledEvent:
    'fake-appointment-cancellation-requested-topic',
  twilioAccountSid: 'fake-account-sid',
  twilioAuthToken: 'fake-auth-token',
  twilioEmailVerificationServiceId: 'fake-verification-sid',
  twilioRemoveWaitlistUrl: 'fake-twilio-url',
  updateAccountTopicName: 'fake-account-topic',
  updatePersonTopicName: 'fake-person-topic',
  paymentsKeyPrivate: 'mock private',
  paymentsKeyPublic: 'mock public',
  sendgridApiKey: 'key',
  ipStackApiUrl: 'ip-stack-url',
  ipStackApiKey: 'ip-stack-key',
  insuranceEligibilityApiRequestUrl:
    'mock-insurance-eligibility-api-request-url',
  waystarInsuranceEligibilityApiUserId:
    'mock-waystar-insurance-eligibility-api-user-id',
  waystarInsuranceEligibilityApiPassword:
    'mock-waystar-insurance-eligibility-api-password',
  mapboxApiUrl: 'mapbox-url',
  mapboxAccessToken: 'mapbox-access-token',
  jwtTokenSecretKey: 'jwt-token-secret-key',
  accountTokenExpiryTime: 1800,
  orderNumberBlockLength: 5,
  alwaysAllowedFeatureFlags: [],
  appInsightInstrumentationKey: 'app-insights-instrumentation-key',
  appInsightServiceName: 'app-insights-service-name',
  cancelAppointmentWindowExpiryTimeInHours: 0,
  certificates: {
    pfxFile: 'pfx-file',
    pfxPass: 'pfx-pass',
  },
  connectionString: 'connection-string',
  corsWhiteList: [],
  deviceTokenExpiryTime: 10,
  environment: 'environment',
  healthBotAppSecret: 'health-bot-app-secret',
  healthBotDefaultLocale: 'health-bot-default-locale',
  healthBotDirectLineTokenEp: 'health-bot-direct-line-token-ep',
  healthBotWebchatSecret: 'health-bot-webchat-secret',
  jwtTokenExpiryTime: 10,
  logger: {} as Logger,
  maxIdentityVerificationAttempts: 5,
  maxPinVerificationAttempts: 4,
  port: 1000,
  smartPriceProcessorControllerNumber: 'X01',
  smartPriceRxGroup: '200P32F',
  myrxIdentityTenantId: 'myrx-tenant-id',
  topicCommonBusinessEvent: 'fake-common-business-topic',
  topicCommonMonitoringEvent: 'fake-common-monitoring-topic',
};
