// Copyright 2020 Prescryptive Health, Inc.

export type ResponseCode<T> = { code: T };

export type ProviderLocationRequestValidationCodes =
  | 'LOCATION_ID_REQUIRED'
  | 'SERVICE_TYPE_REQUIRED'
  | 'START_DATE_REQUIRED'
  | 'END_DATE_REQUIRED'
  | 'ORDER_NUMBER_REQUIRED';

export type AddMembershipRequestValidationCodes =
  | 'FIRSTNAME_REQUIRED'
  | 'LASTNAME_REQUIRED'
  | 'PRIMARY_RX_ID_REQUIRED'
  | 'DATE_OF_BIRTH_REQUIRED'
  | 'MAX_LENGTH_EXCEEDED'
  | 'INVALID_DATE_FORMAT';

export type RecoveryEmailValidationCodes =
  | 'EMAIL_REQUIRED'
  | 'INVALID_EMAIL_ADDRESS'
  | 'NEW_EMAIL_REQUIRED'
  | 'OLD_EMAIL_REQUIRED';

export type FavoritedPharmaciesValidationCodes = 'INVALID_FAVORITED_PHARMACIES';

export type WaitlistValidationCodes =
  | 'SERVICETYPE_REQUIRED'
  | 'ZIPCODE_REQUIRED'
  | 'INVALID_LENGTH_ZIPCODE'
  | 'MILES_REQUIRED'
  | 'TO_REQUIRED'
  | 'ACCOUNT_SID_REQUIRED'
  | 'MESSAGE_SID_REQUIRED'
  | 'MESSAGE_BODY_REQUIRED'
  | 'MESSAGE_FROM_REQUIRED'
  | 'MESSAGE_FROM_CITY_REQUIRED'
  | 'MESSAGE_FROM_STATE_REQUIRED'
  | 'MESSAGE_FROM_ZIP_REQUIRED';

export type PinResetValidationCodes =
  | 'VERIFICATION_TYPE_REQUIRED'
  | 'VERIFICATION_TYPE_INVALID'
  | 'VERIFICATION_CODE_REQUIRED'
  | 'VERIFICATION_CODE_INVALID'
  | 'MASKED_VALUE_REQUIRED';

export type PrescriptionRequestValidationCodes =
  | 'PHARMACY_NCPDP_REQUIRED'
  | 'PRESCRIPTION_IDENTIFIER_REQUIRED';

export type CreateAccountRequestValidationCodes =
  | 'FIRSTNAME_REQUIRED'
  | 'LASTNAME_REQUIRED'
  | 'MAX_LENGTH_EXCEEDED'
  | 'DATE_OF_BIRTH_REQUIRED'
  | 'INVALID_DATE_FORMAT'
  | 'EMAIL_ID_REQUIRED'
  | 'INVALID_EMAIL_ID'
  | 'CODE_REQUIRED'
  | 'INVALID_CODE'
  | 'PHONE_NUMBER_REQUIRED'
  | 'INVALID_PHONE_NUMBER';

export type VerifyMembershipRequestValidationCodes =
  | 'FIRSTNAME_REQUIRED'
  | 'LASTNAME_REQUIRED'
  | 'MAX_LENGTH_EXCEEDED'
  | 'DATE_OF_BIRTH_REQUIRED'
  | 'INVALID_DATE_FORMAT'
  | 'EMAIL_ID_REQUIRED'
  | 'INVALID_EMAIL_ID'
  | 'MEMBER_ID_REQUIRED'
  | 'INVALID_MEMBER_ID'
  | 'PHONE_NUMBER_REQUIRED'
  | 'INVALID_PHONE_NUMBER';
