// Copyright 2020 Prescryptive Health, Inc.

export type InternalStringResponseCode =
  | 'DEVICE_TOKEN_MISSING'
  | 'INVALID_DEVICE_TOKEN'
  | 'SHOW_FORGET_PIN'
  | 'INVALID_PIN_KEY'
  | 'REQUIRE_USER_VERIFY_PIN'
  | 'PHONE_NUMBER_MISMATCHED'
  | 'PERSON_NOT_FOUND'
  | 'REQUIRE_USER_REGISTRATION'
  | 'REQUIRE_USER_SET_PIN'
  | 'SESSION_VALID'
  | 'SHOW_ACCOUNT_LOCKED';
