schedules:
  - cron: '0 13 * * Mon-Fri'
    displayName: M-F 8:00 AM (UTC - 5h)
    branches:
      include:
        - master

#To run on a schedule PR and CI triggers must be disabled.
pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: playwright
    displayName: Run Tests using Playwright
    variables:
      - group: variablegroup-keyvault-west-test
    jobs:
      - job: setup
        displayName: Install Node Yarn & Playwright
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 16.13.2

          - task: npmAuthenticate@0
            inputs:
              workingFile: .npmrc
              condition: succeeded()

          - task: YarnInstaller@3
            inputs:
              versionSpec: '1.x'
            continueOnError: false

          - script: |
              yarn setup:options
            displayName: Load dependencies from cache
            workingDirectory: .
            continueOnError: false

          - script: |
              npx playwright install --with-deps
            displayName: 'Install Playwright Browsers'
            workingDirectory: './packages/testing'

          - template: azure-pipelines-step-run-playwright-template.yml

          - publish: './packages/testing/playwright-report'
            artifact: playwright-report
            # always create the artifact, this is useful for debugging failed tests
            condition: always()
