// Copyright 2021 Prescryptive Health, Inc.

import { IAccumulators } from '../../../models/accumulators';
import { IClaimHistory } from '../../../models/claim';
import { IPrescriptionInfo } from '../../../models/prescription-info';
import { IMedicineCabinetState } from '../state/medicine-cabinet/medicine-cabinet.state';

export const prescriptionsMock: IPrescriptionInfo[] = [
  {
    drugName: 'Drug-1',
    ndc: '11111',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: 'mock',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-04-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-2',
    ndc: '11112',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: 'mock-pharmacy',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-05-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-3',
    ndc: '11113',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '3',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-06-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-4',
    ndc: '11114',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '4',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-07-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-5',
    ndc: '11115',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '5',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-08-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-6',
    ndc: '11116',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '6',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-09-28',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-7',
    ndc: '11117',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '7',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-10-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-8',
    ndc: '11118',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '8',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-03-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-9',
    ndc: '11119',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '9',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-02-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-10',
    ndc: '11110',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '10',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2021-01-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-11',
    ndc: '21101',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '11',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2020-12-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
  {
    drugName: 'Drug-12',
    ndc: '21102',
    form: 'form',
    organizationId: 'organization-id',
    prescriptionId: '12',
    primaryMemberRxId: 'primary-member-rx-id',
    refills: 1,
    strength: '2',
    quantity: 3,
    unit: 'unit',
    zipCode: 'zip-code',
    pharmacy: {
      name: 'pharmacy',
      address: {
        lineOne: 'pharmacy-line-one',
        lineTwo: 'pharmacy-line-two',
        city: 'pharmacy-city',
        state: 'pharmacy-state',
        zip: 'pharmacy-zip',
      },
      phoneNumber: '000-000-0000',
      hours: [],
      twentyFourHours: true,
      ncpdp: 'pharmacy-ncpcp',
      isMailOrderOnly: false,
    },
    authoredOn: '2020-11-01',
    orderDate: new Date(),
    orderNumber: 'order-number',
  },
];

export const claimHistoryMock: IClaimHistory = {
  claimPdf: '',
  claims: [
    {
      prescriptionId: '2',
      drugName: 'Medicine B',
      ndc: '12345',
      formCode: 'TAB',
      strength: '200mg',
      quantity: 10,
      daysSupply: 20,
      refills: 1,
      orderNumber: '112244',
      practitioner: {
        id: 'practitioner-2',
        name: 'Dr. Two',
        phoneNumber: '2222222222',
      },
      pharmacy: {
        name: 'Rx Pharmacy 2',
        ncpdp: '2',
      },
      filledOn: new Date(),
      billing: {
        memberPays: 3.16,
        deductibleApplied: 3.16,
      },
    },
    {
      prescriptionId: '12',
      drugName: 'Medicine A',
      ndc: '12345',
      formCode: 'TAB',
      strength: '100mg',
      quantity: 20,
      daysSupply: 22,
      refills: 2,
      orderNumber: '112233',
      practitioner: {
        id: 'practitioner-1',
        name: 'Dr. One',
        phoneNumber: '1111111111',
      },
      pharmacy: {
        name: 'Rx Pharmacy 1',
        ncpdp: '1',
      },
      filledOn: new Date(),
      billing: {
        memberPays: 1.86,
        deductibleApplied: 1.86,
      },
    },
  ],
};

export const accumulatorsMock: IAccumulators = {
  individualDeductible: {
    maximum: 1500,
    used: 385.55,
  },
  individualOutOfPocket: {
    maximum: 4000,
    used: 355.55,
  },
  familyDeductible: {
    maximum: 2000,
    used: 485.55,
  },
  familyOutOfPocket: {
    maximum: 5000,
    used: 585.55,
  },
  planDetailsPdf: 'plan-details-pdf',
};

export const medicineCabinetStateMock: IMedicineCabinetState = {
  prescriptions: prescriptionsMock,
  accumulators: accumulatorsMock,
  claimHistory: claimHistoryMock,
};
