// Copyright 2021 Prescryptive Health, Inc.

import {
  IProfile,
  IPrimaryProfile,
  IDependentProfile,
} from '../../../models/member-profile/member-profile-info';

export const cashProfileMock: IProfile = {
  rxGroupType: 'CASH',
  primary: {
    email: '',
    firstName: 'ME',
    identifier: '6000b2fa965fa7b37c00a7b2',
    isLimited: false,
    isPhoneNumberVerified: false,
    isPrimary: false,
    lastName: 'TEST',
    phoneNumber: '',
    primaryMemberFamilyId: 'CA7F7K',
    primaryMemberPersonCode: '01',
    primaryMemberRxId: 'CA7F7K01',
    age: 4,
    rxGroupType: 'CASH',
    rxSubGroup: 'CASH01',
  } as IPrimaryProfile,
  childMembers: [
    {
      email: '',
      firstName: 'TEST',
      identifier: '6000b2fa965fa7b37c00a7b3',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: 'TEST',
      phoneNumber: '',
      primaryMemberFamilyId: 'CA7F7K',
      primaryMemberPersonCode: '03',
      primaryMemberRxId: 'CA7F7K03',
      rxSubGroup: 'CASH01',
      age: 4,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'ADULT',
      identifier: '60013af2965fa7b37c00a7b4',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>18',
      phoneNumber: '',
      primaryMemberFamilyId: 'CA7F7K',
      primaryMemberPersonCode: '05',
      primaryMemberRxId: 'CA7F7K05',
      rxSubGroup: 'CASH01',
      age: 20,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'ADULT',
      identifier: '60130fb83068eb8cecfb055d',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>13<18',
      phoneNumber: '',
      primaryMemberFamilyId: 'CA7F7K',
      primaryMemberPersonCode: '04',
      primaryMemberRxId: 'CA7F7K04',
      rxSubGroup: 'CASH01',
      age: 13,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'CHILD',
      identifier: '60131183057357ba4a28b4dd',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>3',
      phoneNumber: '',
      primaryMemberFamilyId: 'CA7F7K',
      primaryMemberPersonCode: '06',
      primaryMemberRxId: 'CA7F7K06',
      rxSubGroup: 'CASH01',
      age: 4,
    } as IDependentProfile,
  ],
};

export const pbmProfileMock: IProfile = {
  rxGroupType: 'SIE',
  primary: {
    email: '',
    firstName: 'ME',
    identifier: '6000b2fa965fa7b37c00a7b2',
    isLimited: false,
    isPhoneNumberVerified: false,
    isPrimary: false,
    lastName: 'TEST',
    phoneNumber: '',
    primaryMemberFamilyId: 'SIECA7F7K',
    primaryMemberPersonCode: '01',
    primaryMemberRxId: 'SIECA7F7K01',
    age: 4,
    dateOfBirth: '01/01/2000',
    rxGroupType: 'SIE',
    rxSubGroup: 'HMA01',
  } as IPrimaryProfile,
  adultMembers: [
    {
      email: '',
      firstName: 'TEST',
      identifier: '6000b2fa965fa7b37c00a7b3',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: 'TEST',
      phoneNumber: '',
      primaryMemberFamilyId: 'SIECA7F7K',
      primaryMemberPersonCode: '03',
      primaryMemberRxId: 'SIECA7F7K03',
      rxSubGroup: 'HMA01',
      age: 4,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'ADULT',
      identifier: '60013af2965fa7b37c00a7b4',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>18',
      phoneNumber: '',
      primaryMemberFamilyId: 'SIECA7F7K',
      primaryMemberPersonCode: '05',
      primaryMemberRxId: 'SIECA7F7K05',
      rxSubGroup: 'HMA01',
      age: 20,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'ADULT',
      identifier: '60130fb83068eb8cecfb055d',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>13<18',
      phoneNumber: '',
      primaryMemberFamilyId: 'SIECA7F7K',
      primaryMemberPersonCode: '04',
      primaryMemberRxId: 'SIECA7F7K04',
      rxSubGroup: 'HMA01',
      age: 13,
    } as IDependentProfile,
    {
      email: '',
      firstName: 'CHILD',
      identifier: '60131183057357ba4a28b4dd',
      isLimited: false,
      isPhoneNumberVerified: false,
      isPrimary: false,
      lastName: '>3',
      phoneNumber: '',
      primaryMemberFamilyId: 'SIECA7F7K',
      primaryMemberPersonCode: '06',
      primaryMemberRxId: 'SIECA7F7K06',
      rxSubGroup: 'HMA01',
      age: 4,
    } as IDependentProfile,
  ],
};

export const profileListMock: IProfile[] = [cashProfileMock, pbmProfileMock];
