# Copyright 2021 Prescryptive Health Inc
from random import randint


def random_n_digits(num):
    """
    Method to generate the random number in between the specific range which is generated by using num parameter
    :param num: Then number in which digit range random number should generate
    :return:
    """
    range_start = 10 ** (num-1)
    range_end = (10 ** num)-1
    return randint(range_start, range_end)


def generate_otp():
    """
    Method to generate the otp
    :return: the random int which is returned from random_n_digits method
    """
    return random_n_digits(6)
