// Copyright 2020 Prescryptive Health, Inc.

export enum AppointmentActionKeysEnum {
  APPOINTMENT_SET_SURVEY_QUESTIONS = 'APPOINTMENT_SET_SURVEY_QUESTIONS',
  APPOINTMENT_SET_SELECTED_LOCATION = 'APPOINTMENT_SET_SELECTED_LOCATION',
  APPOINTMENT_SET_CALENDAR_STATUS = 'APPOINTMENT_SET_CALENDAR_STATUS',
  APPOINTMENT_SET_CALENDAR_MONTH = 'APPOINTMENT_SET_CALENDAR_MONTH',
  APPOINTMENT_SET_CALENDAR_DATE = 'APPOINTMENT_SET_CALENDAR_DATE',
  APPOINTMENT_RESET_STATE = 'APPOINTMENT_RESET_STATE',
  APPOINTMENT_DETAILS_RESPONSE = 'APPOINTMENT_DETAILS_RESPONSE',
  APPOINTMENT_RESET_NEW_DEPENDENT_ERROR = `APPOINTMENT_RESET_NEW_DEPENDENT_ERROR`,
  CREATE_BOOKING_NEW_DEPENDENT_ERROR = 'CREATE_BOOKING_NEW_DEPENDENT_ERROR',
  APPOINTMENT_SET_INVITE_CODE = 'APPOINTMENT_SET_INVITE_CODE',
  APPOINTMENT_CHANGE_SLOT = 'APPOINTMENT_CHANGE_SLOT',
  APPOINTMENT_CHANGE_SLOT_ERROR = 'APPOINTMENT_CHANGE_SLOT_ERROR',
}

export type AppointmentActionKeys = keyof typeof AppointmentActionKeysEnum;
export interface IAppointmentAction<T extends AppointmentActionKeys, P> {
  readonly type: T;
  readonly payload: P;
}
