// Copyright 2021 Prescryptive Health, Inc.

export enum IdentityVerificationActionKeysEnum {
  SET_IDENTITY_VERIFICATION_DATA = 'SET_IDENTITY_VERIFICATION_DATA',
  SET_IDENTITY_VERIFICATION_EMAIL_FLAG = 'SET_IDENTITY_VERIFICATION_EMAIL_FLAG',
  SET_IDENTITY_VERIFICATION_METHOD = 'SET_IDENTITY_VERIFICATION_METHOD',
  SET_IDENTITY_VERIFICATION_ERROR = 'SET_IDENTITY_VERIFICATION_ERROR',
  SET_IDENTITY_VERIFICATION_RESET_ERROR = 'SET_IDENTITY_VERIFICATION_RESET_ERROR',
  SET_IDENTITY_VERIFICATION_CODE_SENT = 'SET_IDENTITY_VERIFICATION_CODE_SENT',
  RESET_IDENTITY_VERIFICATION_CODE_SENT = 'RESET_IDENTITY_VERIFICATION_CODE_SENT',
}

export type IdentityVerificationActionKeys =
  keyof typeof IdentityVerificationActionKeysEnum;

export interface IIdentityVerificationAction<
  T extends IdentityVerificationActionKeys,
  P
> {
  readonly type: T;
  readonly payload: P;
}
